session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=
database:
  host: db
  port: 5432
  user: kts_user
  password: kts_pass
  database: kts
common:
  port: 8080
postgres:
  database_url: postgres://kts_user:kts_pass@db/kts
  require_ssl: false
admin:
  email: admin@admin.com
  password: admin
bot:
  token: 5617018832:AAGD8rIf7dQsT12cOUzzVzgI6nTeNeeVWPc